= Alternatives


== Minikube

It is possible to use https://minikube.sigs.k8s.io[Minikube] for testing. In order to create a suitable cluster, execute
the following command:

[source,bash]
----
minikube start --cpus 8 --memory 24576 --disk-size 20gb --addons ingress
----

== Using AWS alternatives for production

It is possible to use AWS compatible services, and Kafka instead of SQS/SNS.However, it is up to the user to provide
such services. You can follow the instructions in xref:cluster-preparing.adoc[Preparing the environment], and
create API compatible replacements.

== Using AWS alternatives for testing

In order to set up an infrastructure suitable for testing, you can use our provided "infrastructure" Helm chart.

[NOTE]
====
The testing infrastructure is highly opinionated and will only work with Minikube.
====

To install this, run the following command:

[source,bash]
----
cd deploy/k8s
kubectl create ns trustification
helm upgrade --install -n trustification infrastructure charts/trustification-infrastructure --values values-minikube.yaml --set-string keycloak.ingress.hostname=sso.$(minikube ip).nip.io --set-string appDomain=.$(minikube ip).nip.io
----

Then, you need to use the same `values-minishift.yaml` values file for installing the actual deployment.

IMPORTANT: It is required to keep the same settings, and even the namespace of the example commands. Otherwise, it won't
work.
