= Pre-requisites

In order to install Trustification on a Kubernetes cluster, you will need:

* A few command line tools on your local machine
** `kubectl` (or `oc`)
** `helm`
** `git`
** An editor of your choice
* To use `bash` as your shell
* A Kubernetes cluster
** Including support for the `Ingress` resource
** Access to the cluster from your local machine, using `kubectl`
** DNS set up in a way that, based on an "application domain", it is possible to build all other domains
* Storage and events
** Either AWS S3 and SQS/SNS
** Or another S3 compatible service, with support for Kafka change notifications
* OpenID Connect
** An OpenID connect service for authentication, like Keycloak

== Minikube

It is possible to use https://minikube.sigs.k8s.io[Minikube] for testing. In order to create a suitable cluster, execute
the following command:

[source,bash]
----
minikube start --cpus 8 --memory 24576 --disk-size 20gb --addons ingress
----

== OpenShift

A default OpenShift cluster with publicly trusted TLS setup.

NOTE: CRC does not provide a TLS setup with a publicly known trust anchor. Therefor it will not work at the moment.

It is possible to replace all `kubectl` commands with `oc`.
