= Before you start

A few tips you might find useful before you start.

== Pre-requisites

To install Trustification on a Kubernetes cluster, you will need:

* A few command line tools on your local machine
** `kubectl` (or `oc`)
** `helm`
** `git`
** An editor of your choice
* To use `bash` as your shell
* A Kubernetes cluster
** Including support for the `Ingress` resource
** Access to the cluster from your local machine, using `kubectl`
** DNS is set up in a way that, based on an "application domain", it is possible to build all other domains
* Storage and events
** Either AWS S3 and SQS/SNS
** Or another S3 compatible service, with support for Kafka change notifications
* OpenID Connect
** An OpenID Connect service for authentication, like Keycloak

== Kubernetes Namespace

This documentation will use `trustification` as the default namespace for the installation.
It is possible to use a different name, but you will need to adapt the following commands, replacing the use of
`trustification` as a namespace with your actual namespace.

NOTE: Not every time `trusification` is used as a Kubernetes namespace, be sure to not just search & replace all occasions of `trustification`.
