{
 "title": "Trustification AWS",
 "description": "Monitoring of AWS resources",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "S3 Bombastic Bucket Size (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_s3_bucket_size_bytes_average{dimension_BucketName=~\"bombastic.*\"}",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "S3 Vexination Bucket Size (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_s3_bucket_size_bytes_average{dimension_BucketName=~\"vexination.*\"}",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Vexination S3 Objects (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "aws_s3_number_of_objects_average{dimension_BucketName=~\"vexination.*\"}",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "S3 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "aws_s3_5xx_errors_average", "legendFormat": "{{dimension_BucketName}}" }
   ]
  },
  {
   "title": "Bombastic S3 Objects (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "aws_s3_number_of_objects_average{dimension_BucketName=~\"bombastic.*\"}",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "S3 4xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "aws_s3_4xx_errors_average", "legendFormat": "{{dimension_BucketName}}" }
   ]
  }
 ]
}