{
 "title": "Trustification SLO",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "VEX indexing failures",
   "type": "timeseries",
   "description": "Percentage of VEX documents that failed to index successfully (Lower is better).",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(namespace) (rate(index_failed_total{pod =~ \"vexination-indexer.*\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(index_indexed_total{pod =~ \"vexination-indexer.*\", namespace = \"$namespace\"}[30m])))\n",
     "legendFormat": "vexination"
    }
   ]
  },
  {
   "title": "SBOM indexing failures",
   "type": "timeseries",
   "description": "Percentage of SBOM documents that failed to index successfully (Lower is better).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(namespace) (rate(index_failed_total{pod =~ \"bombastic-indexer.*\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(index_indexed_total{pod =~ \"bombastic-indexer.*\", namespace = \"$namespace\"}[30m])))\n",
     "legendFormat": "bombastic"
    }
   ]
  },
  {
   "title": "Percentage of requests that failed (status code = 5xx)",
   "type": "timeseries",
   "description": "Percentage of requests that failed (status code = 5xx) (Lower is better).",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(namespace) (rate(bombastic_api_http_requests_total{status =~ \"5..\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(bombastic_api_http_requests_total{status !~ \"5..\", namespace = \"$namespace\"}[30m])))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "(sum by(namespace) (rate(vexination_api_http_requests_total{status =~ \"5..\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(vexination_api_http_requests_total{status !~ \"5..\", namespace = \"$namespace\"}[30m])))",
     "legendFormat": "vexination"
    },
    {
     "expr": "(sum by(namespace) (rate(spog_api_http_requests_total{status =~ \"5..\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(spog_api_http_requests_total{status !~ \"5..\", namespace = \"$namespace\"}[30m])))",
     "legendFormat": "spog"
    }
   ]
  },
  {
   "title": "Percentage of the search request response times above 1s",
   "type": "timeseries",
   "description": "Percentage of the search request response times above 1s (Lower is better).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1.0 - (sum(rate(bombastic_api_http_requests_duration_seconds_bucket{exported_endpoint=\"/api/v1/sbom/search\", namespace = \"$namespace\", status !~ \"5..\", le=\"1\"}[10m])) by (namespace) / sum(rate(bombastic_api_http_requests_duration_seconds_count{exported_endpoint=\"/api/v1/sbom/search\", namespace = \"$namespace\", status !~ \"5..\" }[10m])) by (namespace))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "1.0 - (sum(rate(vexination_api_http_requests_duration_seconds_bucket{exported_endpoint=\"/api/v1/vex/search\", namespace = \"$namespace\", status !~ \"5..\", le=\"1\"}[10m])) by (namespace) / sum(rate(vexination_api_http_requests_duration_seconds_count{exported_endpoint=\"/api/v1/vex/search\", namespace = \"$namespace\", status !~ \"5..\"}[10m])) by (namespace))",
     "legendFormat": "vexination"
    },
    {
     "expr": "1.0 - (sum(rate(spog_api_http_requests_duration_seconds_bucket{exported_endpoint=~\"/api/v1/.*/search\", namespace = \"$namespace\", status !~ \"5..\", le=\"1\"}[10m])) by (namespace) / sum(rate(spog_api_http_requests_duration_seconds_count{exported_endpoint=~\"/api/v1/.*/search\", namespace = \"$namespace\", status !~ \"5..\"}[10m])) by (namespace))",
     "legendFormat": "spog"
    }
   ]
  }
 ]
}