{
 "title": "Trustification Performance",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "API request latency p99 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(spog_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "spog"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(bombastic_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vexination_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "vexination"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(v11y_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "v11y"
    }
   ]
  },
  {
   "title": "API request throughput (requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(spog_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "spog"
    },
    {
     "expr": "sum(rate(bombastic_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "sum(rate(vexination_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "vexination"
    },
    {
     "expr": "sum(rate(v11y_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "v11y"
    }
   ]
  },
  {
   "title": "Indexing Throughput (documents/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(index_indexed_total{namespace = \"$namespace\", pod=~\"bombastic-indexer.*\"}[10m]))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "sum(rate(index_indexed_total{namespace = \"$namespace\", pod=~\"v11y-indexer.*\"}[10m]))",
     "legendFormat": "v11y"
    },
    {
     "expr": "sum(rate(index_indexed_total{namespace = \"$namespace\", pod=~\"vexination-indexer.*\"}[10m]))",
     "legendFormat": "vexination"
    }
   ]
  }
 ]
}