FROM ghcr.io/ctron/trunk:0.5.1 as builder

ARG tag

# cannot use /usr/src as it is configured as `VOLUME` in the base image, which seems to be an issue
# for buildah (not for podman build): https://github.com/containers/buildah/issues/4845

RUN mkdir /trustification

COPY . /trustification

RUN ls /trustification

WORKDIR /trustification/spog/ui

RUN true \
    && npm ci \
    && rustup target add wasm32-unknown-unknown \
    && env TAG=$tag trunk build --release --dist /public

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

LABEL org.opencontainers.image.source="https://github.com/trustification/trustification"

RUN microdnf install -y nginx jq

RUN true \
    && mkdir /public \
    && mkdir /endpoints

COPY --from=builder /public /public/
COPY spog/ui/config/nginx.conf /etc/nginx/nginx.conf

COPY spog/ui/config/nginx.sh /nginx.sh
RUN chmod a+x /nginx.sh

EXPOSE 80

CMD [ "/nginx.sh" ]
