FROM ghcr.io/ctron/trunk:latest as builder

RUN mkdir /usr/src/trustification

COPY . /usr/src/trustification

RUN ls /usr/src/trustification

WORKDIR /usr/src/trustification/spog/ui

RUN true \
    && npm ci \
    && rustup target add wasm32-unknown-unknown \
    && trunk build --release --dist /public

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

LABEL org.opencontainers.image.source="https://github.com/trustification/trustification"

RUN microdnf install -y nginx jq

RUN true \
    && mkdir /public \
    && mkdir /endpoints

COPY --from=builder /public /public/
COPY spog/ui/config/nginx.conf /etc/nginx/nginx.conf

COPY spog/ui/config/nginx.sh /nginx.sh
RUN chmod a+x /nginx.sh

EXPOSE 80

CMD [ "/nginx.sh" ]
