FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
LABEL org.opencontainers.image.source="https://github.com/trustification/trustification"
RUN microdnf install --nodocs git -y
ENTRYPOINT ["git"]
WORKDIR /git
