{
 "title": "Trustification Performance",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "API request latency p99 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(spog_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "spog"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(bombastic_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vexination_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "vexination"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(v11y_api_http_requests_duration_seconds_bucket{namespace=\"$namespace\"}[10m])))",
     "legendFormat": "v11y"
    }
   ]
  },
  {
   "title": "API request throughput (requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(spog_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "spog"
    },
    {
     "expr": "sum(rate(bombastic_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "sum(rate(vexination_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "vexination"
    },
    {
     "expr": "sum(rate(v11y_api_http_requests_total{namespace = \"$namespace\"}[10m]))",
     "legendFormat": "v11y"
    }
   ]
  },
  {
   "title": "Indexing Throughput (documents/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(index_indexed_total{namespace = \"$namespace\", pod=~\"bombastic-indexer.*\"}[10m]))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "sum(rate(index_indexed_total{namespace = \"$namespace\", pod=~\"v11y-indexer.*\"}[10m]))",
     "legendFormat": "v11y"
    },
    {
     "expr": "sum(rate(index_indexed_total{namespace = \"$namespace\", pod=~\"vexination-indexer.*\"}[10m]))",
     "legendFormat": "vexination"
    }
   ]
  }
 ]
}
{
 "title": "Trustification SLO",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Indexing failures",
   "type": "timeseries",
   "description": "Percentage of documents that failed to index successfully (Lower is better).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(namespace) (rate(index_failed_total{pod =~ \"vexination-indexer.*\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(index_indexed_total{pod =~ \"vexination-indexer.*\", namespace = \"$namespace\"}[30m])))\n",
     "legendFormat": "vexination"
    },
    {
     "expr": "(sum by(namespace) (rate(index_failed_total{pod =~ \"bombastic-indexer.*\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(index_indexed_total{pod =~ \"bombastic-indexer.*\", namespace = \"$namespace\"}[30m])))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "(sum by(namespace) (rate(index_failed_total{pod =~ \"v11y-indexer.*\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(index_indexed_total{pod =~ \"v11y-indexer.*\", namespace = \"$namespace\"}[30m])))",
     "legendFormat": "v11y"
    }
   ]
  },
  {
   "title": "Percentage of requests that failed (status code = 5xx)",
   "type": "timeseries",
   "description": "Percentage of requests that failed (status code = 5xx) (Lower is better).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(namespace) (rate(bombastic_api_http_requests_total{status =~ \"5..\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(bombastic_api_http_requests_total{status !~ \"5..\", namespace = \"$namespace\"}[30m])))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "(sum by(namespace) (rate(vexination_api_http_requests_total{status =~ \"5..\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(vexination_api_http_requests_total{status !~ \"5..\", namespace = \"$namespace\"}[30m])))",
     "legendFormat": "vexination"
    },
    {
     "expr": "(sum by(namespace) (rate(v11y_api_http_requests_total{status =~ \"5..\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(v11y_api_http_requests_total{status !~ \"5..\", namespace = \"$namespace\"}[30m])))",
     "legendFormat": "v11y"
    },
    {
     "expr": "(sum by(namespace) (rate(spog_api_http_requests_total{status =~ \"5..\", namespace = \"$namespace\"}[30m]))) / (sum by(namespace) (rate(spog_api_http_requests_total{status !~ \"5..\", namespace = \"$namespace\"}[30m])))",
     "legendFormat": "spog"
    }
   ]
  },
  {
   "title": "Percentage of the search request response times above 1s",
   "type": "timeseries",
   "description": "Percentage of the search request response times above 1s (Lower is better).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1.0 - (sum(rate(bombastic_api_http_requests_duration_seconds_bucket{exported_endpoint=\"/api/v1/sbom/search\", namespace = \"$namespace\", status !~ \"5..\", le=\"1\"}[10m])) by (namespace) / sum(rate(bombastic_api_http_requests_duration_seconds_count{exported_endpoint=\"/api/v1/sbom/search\", namespace = \"$namespace\", status !~ \"5..\" }[10m])) by (namespace))",
     "legendFormat": "bombastic"
    },
    {
     "expr": "1.0 - (sum(rate(vexination_api_http_requests_duration_seconds_bucket{exported_endpoint=\"/api/v1/vex/search\", namespace = \"$namespace\", status !~ \"5..\", le=\"1\"}[10m])) by (namespace) / sum(rate(vexination_api_http_requests_duration_seconds_count{exported_endpoint=\"/api/v1/vex/search\", namespace = \"$namespace\", status !~ \"5..\"}[10m])) by (namespace))",
     "legendFormat": "vexination"
    },
    {
     "expr": "1.0 - (sum(rate(v11y_api_http_requests_duration_seconds_bucket{exported_endpoint=~\"/api/v1/search\", namespace = \"$namespace\", status !~ \"5..\", le=\"1\"}[10m])) by (namespace) / sum(rate(v11y_api_http_requests_duration_seconds_count{exported_endpoint=~\"/api/v1/search\", namespace = \"$namespace\", status !~ \"5..\"}[10m])) by (namespace))",
     "legendFormat": "v11y"
    },
    {
     "expr": "1.0 - (sum(rate(spog_api_http_requests_duration_seconds_bucket{exported_endpoint=~\"/api/v1/.*/search\", namespace = \"$namespace\", status !~ \"5..\", le=\"1\"}[10m])) by (namespace) / sum(rate(spog_api_http_requests_duration_seconds_count{exported_endpoint=~\"/api/v1/.*/search\", namespace = \"$namespace\", status !~ \"5..\"}[10m])) by (namespace))",
     "legendFormat": "spog"
    }
   ]
  }
 ]
}