FROM registry.access.redhat.com/ubi9/ubi:latest as builder

RUN dnf install -y gcc openssl openssl-devel cmake gcc-c++ git curl-minimal unzip

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
ENV PATH "$PATH:/root/.cargo/bin"

ARG protoc_version="23.4"
RUN mkdir protoc && cd protoc && \
    curl -sSL https://github.com/protocolbuffers/protobuf/releases/download/v${protoc_version}/protoc-${protoc_version}-linux-x86_64.zip -o protoc.zip && \
    unzip protoc.zip && \
    install bin/protoc /usr/local/bin && \
    cd .. && rm -Rf protoc && \
    protoc --version

RUN mkdir /usr/src/project
COPY . /usr/src/project
WORKDIR /usr/src/project

ARG tag
RUN TAG=$tag cargo test --no-run -p integration-tests --release --features acceptance-tests
RUN mkdir -p test-binaries
RUN find target/release/deps/ -type f ! -name "*.*" ! -name "integration_tests*" | xargs -I{} cp {} test-binaries/

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

LABEL org.opencontainers.image.source="https://github.com/trustification/trustification"

COPY --from=builder /usr/src/project/test-binaries /tests
COPY --from=builder /usr/src/project/integration-tests/run-test-binaries.sh /

ENV RUST_LOG info

ENTRYPOINT ["/run-test-binaries.sh"]
