FROM ghcr.io/ctron/trunk:latest as builder

RUN mkdir /trustification

COPY . /trustification

RUN ls /trustification/docs

WORKDIR /trustification/docs

RUN true \
    && npm ci \
    && make

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

LABEL org.opencontainers.image.source="https://github.com/trustification/trustification"

RUN microdnf install -y nginx jq

RUN true \
    && mkdir /public

COPY --from=builder /trustification/docs/build/site /public/
COPY config/nginx.conf /etc/nginx/nginx.conf

COPY config/nginx.sh /nginx.sh
RUN chmod a+x /nginx.sh

EXPOSE 8080

CMD [ "/nginx.sh" ]
