= SBOM

Bombastic allows you to publish, retreive and search for Software Bill of Materials (SBOM) documents.

Bombastic supports searching SBOM data using the xref:search.adoc[sikula query language].

The Bombastic REST API can be used to publish and retrieve an SBOM using an identifier such a product identifier (CPE) or package URL (pURL).

== Publish

To publish an SBOM:

[source,bash]
----
curl -H "transfer-encoding: chunked" --json sbom.json https://sbom.trustification.dev/api/v1/sbom?id=my-sbom
----

NOTE: The SBOM must be in one of CycloneDX or SPDX formats.

If you got a `201 Created` in the response, the document was published successfully. See the link:https://sbom.trustification.dev/swagger-ui/[OpenAPI] for more details on potential responses.


NOTE: A document may take between seconds and minutes to appearch in searches.

== Retrieving

To retrieve an SBOM:

[source,bash]
----
curl https://sbom.trustification.dev/api/v1/sbom?id=my-sbom
----

== Searching

By default queries search through identifiers, titles and descriptions in the SBOM, and returns the matching results ordered by a relevance.

See the xref:search.adoc[sikula query language] for more details on the search syntax.

=== Qualifiers

The table below contains a list of the qualifiers you can use when searching Bombastic:

[cols="1,1,1,1"]
|===
| *Qualifier* | *Description* | *Matching* | *Example*
| `package` | Search in by package identifiers | Exact, Partial | `package:"pkg:maven/io.seedwing/seedwing-java-example@1.0.0-SNAPSHOT?type=jar"`
| `type` | Search by type | Exact | `type:oci`
| `namespace` | Search by namespace | Exact | `namespace:io.quarkus`
| `version` | Search by version | Exact, Partial | `2.13 in:version`
| `description` | Search by description | Term | `description:how`
| `created` | Search by created date | Exact, Range | `created:2022-01-01..2023-01-01`
| `digest` | Search by SBOM digest | Exact | `digest:5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03`
| `license` | Search by license | Exact | `license:Apache-2.0`
| `supplier` | Search by supplier | Exact, Partial | `"Red Hat" in:supplier`
| `qualifier` | Search in package URL qualifiers | Exact | `qualifier:tag:7.9-1057`
| `dependency` | Search in package dependencies | Exact, Partial | `dependency:openssl`
|===

TIP: Matching can either be Exact (Contains exactly a value), Partial (Prefix matching of value), Term (Inverse index aka. text matching) or Range (for values that can match within a range)

NOTE: You can also enforce an ordering on the results for the `created` field: `ubi9 sort:created` or `ubi9 -sort:created`.

=== Use cases

==== Find packages that contain openssl and has the Apache 2.0 license

[source,rust]
----
dependency:openssl license:"Apache-2.0"
----

==== Find all container packages

[source,rust]
----
type:oci
----

=== Reference

See the full link:https://sbom.trustification.dev/swagger-ui/[Bombastic API documentation] for more details.

[id="creating-an-sbom-manifest-file"]
== Creating an SBOM manifest file

Trustification can analyze both CycloneDX and Software Package Data Exchange (SPDX) SBOM formats using the JSON file format.
Many open-source tools are available to you for creating Software Bill of Materials (SBOM) manifest files from container images, or for your application.
For this procedure we are going to use the Syft tool.

IMPORTANT: Currently, Trustification only supports CycloneDX version 1.3, and SPDX version 2.2.

.Prerequisites
* Install link:https://github.com/anchore/syft#installation[Syft] for your workstation platform.

.Procedure
. To create an SBOM by using a container image.
+
**CycloneDX format:**
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
syft _IMAGE_PATH_ -o cyclonedx-json
----
+
.Example
[source,bash]
----
$ syft registry:example/image:tag -o cyclonedx-json
----
+
**SPDX format:**
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
syft _IMAGE_PATH_ -o spdx-json
----
+
.Example
[source,bash]
----
$ syft registry:example/image:tag -o spdx-json
----
+
NOTE: Syft supports many types of container image sources. See the official supported source list on Syft’s GitHub site.

. To create an SBOM by scanning the local file system.
+
**CycloneDX format:**
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
syft dir: _DIRECTORY_PATH_ -o cyclonedx-json
syft file: _FILE_PATH_ -o cyclonedx-json
----
+
.Example
[source,bash]
----
$ syft dir:. -o cyclonedx-json
$ syft file:/example-binary -o cyclonedx-json
----
+
**SPDX format:**
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
syft dir: _DIRECTORY_PATH_ -o spdx-json
syft file: _FILE_PATH_ -o spdx-json
----
+
.Example
[source,bash]
----
$ syft dir:. -o spdx-json
$ syft file:/example-binary -o spdx-json
----

.Additional resources
* National Telecommunications and Information Administration’s (NTIA) link:https://www.ntia.gov/files/ntia/publications/howto_guide_for_sbom_generation_v1.pdf[How-to Guide on SBOM generation].
