[id="sbom"]
= Software Bill of Materials

Software Bill of Materials (SBOM) is a manifest of software components and dependencies that makes up an application.
The Bombastic service allows you to publish, retrieve, and search for SBOM documents by using a REST API.
Bombastic supports searching SBOM data by using the xref:search.adoc[sikula simple query language].
Publishing and retrieving an SBOM document uses a product's identification in the Common Platform Enumeration (CPE) format, or by a package URL (pURL).

[id="publishing-an-sbom-doc"]
== Publishing a Software Bill of Materials document

You can publish SBOM documents by using CycloneDX version 1.3, or Software Package Data Exchange (SPDX) version 2.2 formats, and the SBOM document must be in a JSON file format.

NOTE: A document can take between a few seconds to minutes before appearing in search results.

.Prerequisite
* An SBOM document.

.Procedure
. To publish an SBOM document to Trustification:
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
curl -H "transfer-encoding: chunked" --json _FILE_NAME_ https://sbom.trustification.dev/api/v1/sbom?id=_SBOM_NAME_
----
+
.Example
[source,bash]
----
$ curl -H "transfer-encoding: chunked" --json sbom-example.json https://sbom.trustification.dev/api/v1/sbom?id=my-sbom-example
----
+
A `201 Created` response means the document was successfully published.

.Additional resources
* See the link:https://sbom.trustification.dev/swagger-ui/[OpenAPI] documentation for more details on potential responses.

[id="retrieving-an-sbom"]
== Retrieving a Software Bill of Materials

You can retrieve SBOM documents by specifying a product's identification.

.Prerequisite
* A CPE identifier or pURL. 

.Procedure
. To retrieve an SBOM document from Trustification:
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
curl https://sbom.trustification.dev/api/v1/sbom?id=_SBOM_NAME_
----
+
.Example
[source,bash]
----
$ curl https://sbom.trustification.dev/api/v1/sbom?id=my-sbom-example
----

[id="search-for-an-sbom-doc"]
== Search for Software Bill of Materials document

By default, queries search for identifiers, titles, and descriptions within the SBOM document, and returns the matching results ordered by relevance.

See the xref:search.adoc[sikula simple query language] for more details on the search syntax.

[id="search-qualifiers"]
=== Search qualifiers

The following table has a list of the search qualifiers you can use when searching the Bombastic service.

[cols="1,1,1,1"]
|===
| *Qualifier* | *Description* | *Matching Type* | *Example*
| `package` | Search in by package identifiers | Exact, Partial | `package:"pkg:maven/io.seedwing/seedwing-java-example@1.0.0-SNAPSHOT?type=jar"`
| `type` | Search by type | Exact | `type:oci`
| `namespace` | Search by namespace | Exact | `namespace:io.quarkus`
| `version` | Search by version | Exact, Partial | `2.13 in:version`
| `description` | Search by description | Term | `description:how`
| `created` | Search by created date | Exact, Range | `created:2022-01-01..2023-01-01`
| `digest` | Search by SBOM digest | Exact | `digest:5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03`
| `license` | Search by license | Exact | `license:Apache-2.0`
| `supplier` | Search by supplier | Exact, Partial | `"Red Hat" in:supplier`
| `qualifier` | Search in package URL qualifiers | Exact | `qualifier:tag:7.9-1057`
| `dependency` | Search in package dependencies | Exact, Partial | `dependency:openssl`
|===

The four matching types are:
* An **Exact** match has the exact value.
* A **Partial** match is a prefix value.
* A **Term** match is text matching.
* A **Range** match is values within a range.

NOTE: You can also enforce an ordering on the results for the `created` field, for example, `ubi9 sort:created` or `ubi9 -sort:created`.

[id="sbom-use-cases"]
=== Use cases

The following uses cases illustrate how you can link:https://trustification.dev/package/search/[search Trustification] to find SBOM documents.

IMPORTANT: Enable **Complex** searching before running these queries.

==== Searching for packages that contain `openssl` and has the Apache 2.0 license

.Example
[source,rust]
----
dependency:openssl license:"Apache-2.0"
----

==== Searching for all container packages

.Example
[source,rust]
----
type:oci
----

[id="sbom-reference"]
=== Reference

See the full link:https://sbom.trustification.dev/swagger-ui/[Bombastic API documentation] for more details.

[id="creating-an-sbom-manifest-file"]
== Creating an SBOM manifest file

Trustification can analyze both CycloneDX and Software Package Data Exchange (SPDX) SBOM formats using the JSON file format.
Many open-source tools are available to you for creating Software Bill of Materials (SBOM) manifest files from container images, or for your application.
For this procedure we are going to use the Syft tool.

IMPORTANT: Currently, Trustification only supports CycloneDX version 1.3, and SPDX version 2.2.

.Prerequisites
* Install link:https://github.com/anchore/syft#installation[Syft] for your workstation platform.

.Procedure
. To create an SBOM by using a container image.
+
**CycloneDX format:**
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
syft _IMAGE_PATH_ -o cyclonedx-json
----
+
.Example
[source,bash]
----
$ syft registry:example/image:tag -o cyclonedx-json
----
+
**SPDX format:**
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
syft _IMAGE_PATH_ -o spdx-json
----
+
.Example
[source,bash]
----
$ syft registry:example/image:tag -o spdx-json
----
+
NOTE: Syft supports many types of container image sources. See the official supported source list on Syft’s GitHub site.

. To create an SBOM by scanning the local file system.
+
**CycloneDX format:**
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
syft dir: _DIRECTORY_PATH_ -o cyclonedx-json
syft file: _FILE_PATH_ -o cyclonedx-json
----
+
.Example
[source,bash]
----
$ syft dir:. -o cyclonedx-json
$ syft file:/example-binary -o cyclonedx-json
----
+
**SPDX format:**
+
.Syntax
[source,bash,subs="verbatim,quotes"]
----
syft dir: _DIRECTORY_PATH_ -o spdx-json
syft file: _FILE_PATH_ -o spdx-json
----
+
.Example
[source,bash]
----
$ syft dir:. -o spdx-json
$ syft file:/example-binary -o spdx-json
----

.Additional resources
* National Telecommunications and Information Administration’s (NTIA) link:https://www.ntia.gov/files/ntia/publications/howto_guide_for_sbom_generation_v1.pdf[How-to Guide on SBOM generation].
