= Search and retrieve

Trustification allows you to search for Software Bill of Materials (SBOM) and Vulnerability Exploitability eXchange (VEX) data using a built-in search engine to find relevant data quickly.
Once found, you can also retrieve the original SBOM and VEX data.

You can use the web-based user interface (UI), or the REST APIs for searching SBOM and VEX data.

== The Spog UI

The Spog UI can search link:https://trustification.dev/advisory/search/[advisories] or link:https://trustification.dev/package/search/[packages] for vulnerability data.
For example, from the _Advisories_ page, type **openssl** in the search field and see the results.
You can refine your search criteria by filtering based on the **Severity**, and by **Products**.

You can start searching at link:https://trustification.dev[trustification.dev].

== API query language

Trustification uses the search query language based on link:https://github.com/ctron/sikula[Sikula], which is similar to GitHub's searching syntax.
Referencing fields in the query string depends on the search source.
In general, any free-form text query searches titles and descriptions in the SBOM, and VEX documents, and returns the matching results that the search engine thinks is best.

You can search in specific fields such as `title` using `_QUERY_STRING_ in:title`.
You can use ranges for the date fields: `release:2022-01-01..2022-12-31`.
Also for each service, you can use some short-hand predicates, such as `is:__PREDICATE__`.

== REST APIs

Trustification has three REST APIs that you can use for searching and retrieving.
They differ in what data they search and the expected flow.

* Spog - This API focuses on the needs of the UI, and can make queries to different underlying sources.
* Bombastic - This API searches and retrieve SBOM data only.
* Vexination - this API searches VEX data only.

=== Spog API

With the Spog API you can search and retrieve data on advisories, and packages.

.Syntax
* `GET /api/v1/advisory/search?q=_QUERY_STRING_`
* `GET /api/v1/advisory?id=_ADVISORY_ID_`
* `GET /api/v1/package/search?q=_QUERY_STRING_`
* `GET /api/v1/package?id=_PACKAGE_ID_`

.Examples
* link:https://api.trustification.dev/api/v1/advisory/search?q=openssl[`GET /api/v1/advisory/search?q=openssl`]
* link:https://api.trustification.dev/api/v1/advisory?id=RHSA-2023:1441[`GET /api/v1/advisory?id=RHSA-2023:1441`]

.Additional Information
* See the full link:https://api.trustification.dev/swagger-ui/[Spog API documentation] for more details.

=== Bombastic API

You can search for SBOM data by using the Bombastic API.

.Syntax
* `GET /api/v1/sbom/search?q=_QUERY_STRING_`
* `GET /api/v1/sbom?id=_SBOM_ID_`

.Example
* link:https://sbom.trustification.dev/api/v1/sbom/search?q=openssl[`GET /api/v1/sbom/search?q=openssl`]
* link:https://sbom.trustification.dev/api/v1/sbom?id=vertx-4.0[`GET /api/v1/sbom?id=id=vertx-4.0`]

.Bombastic Fields
* `package-name` - SBOM package name.
* `purl` - SBOM package URL.
* `cpe` - SBOM product identifier.
* `description` - SBOM description.
* `digest` - Artifact digest of package or dependency in SBOM.
* `dependency` - Package name, package URL or CPE of dependency.
* `license` - License of package or dependency.

.Additional Information
* See the full link:https://sbom.trustification.dev/swagger-ui/[Bombastic API documentation] for more details.

=== Vexination API

You can search for VEX data by using the Vexination API.

.Syntax
* `GET /api/v1/vex/search?q=_QUERY_STRING_`
* `GET /api/v1/vex?id=_ADVISORY_ID_`

.Examples
* link:https://vex.trustification.dev/api/v1/vex/search?q=openssl[`GET /api/v1/vex/search?q=openssl`]
* link:https://vex.trustification.dev/api/v1/vex?id=RHSA-2023:1441[`GET /api/v1/vex?id=RHSA-2023:1441`]

.Vexination Fields
* `id` - The advisory identifier.
* `cve` - Common Vulnerabilities and Exposures (CVE) id mentioned in the advisory.
* `title` - Advisory or CVE title.
* `description` - Advisory or CVE description.
* `status` - Advisory status.
* `cvss` - CVSS scores.
* `package` - Affected or fixed packages and products mentioned in product status.
* `affected` - Affected packages and products mentioned in CVEs.
* `fixed` - Fixed packages and products mentioned in CVEs.
* `release` - Advisory or CVE release date.
* `discovery` - Advisory or CVE discovery date.

.Additional Predicates
* `critical` - CVE in critical category.
* `high` - CVE in high category.
* `medium` - CVE in medium category.
* `low` - CVE in low category.

.Additional Examples
* Searching for vulnerabilities mentioning `log4j` in the default fields: link:https://vex.trustification.dev/api/v1/vex?q=log4j[log4j].
* Searching for vulnerabilities mentioning `java` the past 30 days: link:https://vex.trustification.dev/api/v1/vex?q=java+release%3A%3E2023-05-03[java release:>2023-05-03].

.Additional Information
* See the full link:https://vex.trustification.dev/swagger-ui/[Vexination API documentation] for more details.
