= Search

Several Trustification services allow you to search for documents using a simple query language named sikula. The sikula language is similar to what you find when searching GitHub issues.

== The Single Pane of Glass user interface

The Single Pane of Glass (SPoG) UI can search link:https://trustification.dev/advisory/search/[advisories] or link:https://trustification.dev/package/search/[packages] for vulnerability data.
For example, from the _Advisories_ page, type **openssl** in the search field and see the results.
You can refine your search criteria by filtering based on the **Severity**, and by **Products**.

You can start searching at link:https://trustification.dev[trustification.dev].

== REST APIs

Trustification has two REST APIs that you can use for searching. They differ in what data they search and the qualifiers they permit:

* xref:bombastic.adoc[Bombastic] - This API searches SBOM data.
* xref:vexination.adoc[Vexination] - This API searches VEX data.

== Search syntax

Trustification uses the search query language based on link:https://github.com/ctron/sikula[Sikula].

Referencing fields in the query string depends on the search source. In general, any free-form text query searches the default fields as set by the search index.

Multiple terms can be specified, in which case a logical AND will be applied.

=== Logical operators

The following logical operators can be used:

[cols="1,1,1,1"]
|===
| *Operator* | *Example*
| OR | id:foo OR this in:that
| AND | id:foo AND date:>2020-01-01
| NOT | id:foo NOT type:oci
|===

=== Qualifiers

Using qualifiers, you can search on a particular field such as `title`. See the xref:bombastic.adoc[bombastic] or xref:vexination.adoc[vexination] list of qualifiers you can use.

There are four different types of matching that can be done for a qualifier. Which matching type depends on the qualifier, but the possible types are:

* Exact - Contains exactly a value
* Partial - Prefix matching of a value
* Term - Inverse index aka. text matching
* Range - Matches within a range of values

You can use ranges for the date fields: `release:2022-01-01..2022-12-31`.

TIP: If your search term contains a reserved character, such as `:`, you can add quotes.

IMPORTANT: When using the REST API, make sure your query is properly URL-encoded.

=== Predicates

If defined, an index may define a set of short-hand predicates that you can use on the form `is:<predicate>`. Like qualifiers, the possible predicates depends on the service.
