name: Unit Tests

on:
  workflow_call:
  workflow_dispatch:

env:
  GRCOV_VERSION: 0.8.19

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize build space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo rm -Rf ${JAVA_HOME_8_X64}
          sudo rm -Rf ${JAVA_HOME_11_X64}
          sudo rm -Rf ${JAVA_HOME_17_X64}
          sudo rm -Rf ${RUBY_PATH}
          df -h

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            spog/ui/target/
          key: ${{ runner.os }}-unit-${{ hashFiles('**/Cargo.lock') }}

      - name: Install libsasl2-dev
        run: sudo apt-get install -y libsasl2-dev

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install llvm-tools-preview
        run: |
          rustup component add llvm-tools-preview

      - name: Install clang llvm pkg-config nettle-dev
        run: |
          sudo apt install clang llvm pkg-config nettle-dev

      - name: Install grcov
        run: |
          wget https://github.com/mozilla/grcov/releases/download/v${GRCOV_VERSION}/grcov-x86_64-unknown-linux-gnu.tar.bz2
          tar xavf grcov-x86_64-unknown-linux-gnu.tar.bz2
          sudo install grcov /usr/local/bin/

      - name: Print storage use
        run: |
          sudo du -sh *
          sudo du -sh $HOME/*

      - name: Test
        run: |
          cargo xtask test --testset unit --nocapture --concurrent=1

      - name: Upload coverage report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: .coverage/
