C4Container
title Container diagram for Trustification

Person(user, "Incident Response Team", "Incident Response Team")

Container_Boundary(c1, "Internet Banking") {
    Container(spog, "SPoG", "Rust microservices", "Provides unified API and UI for consuming data")
    Container(guac, "GUAC", "Golang services and Postgres DB", "Stores relations between products, packages, vulnerabilities and advisories")
    Container(bombastic, "Bombastic", "Rust microservices", "Stores and indexes SBOMs from external sources. Provides API for searching SBOMs")
    Container(vexination, "Vexination", "Rust microservices", "Stores and indexes VEXs from external sources. Provides API for searching VEXs")
    Container(v11y, "V11y", "Rust microservices", "Stores vulnerability and advisory (CVEs) information")
    ContainerDb(s3, "S3", "S3 compatible storage", "Stores SBOM, VEX and index files")

}

Rel(user, spog, "Uses", "HTTPS")

Rel(spog, guac, "Uses", "JSON/HTTPS")
UpdateRelStyle(spog, guac, $offsetY="60", $offsetX="90")
Rel(spog, bombastic, "Uses", "JSON/HTTPS")
Rel(spog, vexination, "Uses", "JSON/HTTPS")
Rel(spog, v11y, "Uses", "JSON/HTTPS")

Rel(guac, s3, "Reads")
Rel(bombastic, s3, "Reads")
Rel(vexination, s3, "Reads")
